server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    path: /error
    include-stacktrace: always
    include-message: always

logging:
  level:
    ROOT: INFO
    com:
      entando: DEBUG
    org:
      springframework:
        security: debug

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  #CHANGE-IT modify these settings for production or activate Spring profiles to separate config by environment
  auth-url: http://localhost:9080/auth
  client-id: web_app
  client-secret: web_app
  ssl-required: none
  auth-server-url: ${keycloak.auth-url}
  bearer-only: true
  credentials:
    secret: ${keycloak.client-secret}
  realm: jhipster
  resource: ${keycloak.client-id}
  use-resource-role-mappings: true

app:
  version: 1
  name: entando-template
  security:
    auth-server-url: ${keycloak.auth-server-url}
    realm: ${keycloak.realm}
    client-ui: entando-web
