server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    path: /error
    include-stacktrace: always
    include-message: always

logging:
  level:
    ROOT: DEBUG

#https://medium.com/devops-dudes/securing-spring-boot-rest-apis-with-keycloak-1d760b2004e
keycloak:
  auth-url: http://localhost:9080/auth
  client-id: internal
  client-secret: 03e4db4e-f26b-45fb-9874-0dd7b3fd46b7
  ssl-required: none
  auth-server-url: ${keycloak.auth-url}
  bearer-only: true
  credentials:
    secret: ${keycloak.client-secret}
  realm: entando
  resource: ${keycloak.client-id}
  use-resource-role-mappings: true

app:
  version: 1
  name: entando-template
  security:
    auth-server-url: ${keycloak.auth-server-url}
    realm: ${keycloak.realm}
    client-ui: public
